# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/app/show/region/v1/region.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/app/show/region/v1/region.proto',
  package='bilibili.app.show.region.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(bilibili/app/show/region/v1/region.proto\x12\x1b\x62ilibili.app.show.region.v1\"\x19\n\tRegionReq\x12\x0c\n\x04lang\x18\x01 \x01(\t\"G\n\x0bRegionReply\x12\x38\n\x07regions\x18\x01 \x03(\x0b\x32\'.bilibili.app.show.region.v1.RegionInfo\"6\n\x0cRegionConfig\x12\x12\n\nscenesName\x18\x01 \x01(\t\x12\x12\n\nscenesType\x18\x02 \x01(\t\"\x84\x02\n\nRegionInfo\x12\x0b\n\x03tid\x18\x01 \x01(\x05\x12\x0c\n\x04reid\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04logo\x18\x04 \x01(\t\x12\x0c\n\x04goto\x18\x05 \x01(\t\x12\r\n\x05param\x18\x06 \x01(\t\x12\x0b\n\x03uri\x18\x07 \x01(\t\x12\x0c\n\x04type\x18\x08 \x01(\x05\x12\x11\n\tisBangumi\x18\t \x01(\x05\x12\x39\n\x08\x63hildren\x18\n \x03(\x0b\x32\'.bilibili.app.show.region.v1.RegionInfo\x12\x39\n\x06\x63onfig\x18\x0b \x03(\x0b\x32).bilibili.app.show.region.v1.RegionConfig2d\n\x06Region\x12Z\n\x06Region\x12&.bilibili.app.show.region.v1.RegionReq\x1a(.bilibili.app.show.region.v1.RegionReplyb\x06proto3'
)




_REGIONREQ = _descriptor.Descriptor(
  name='RegionReq',
  full_name='bilibili.app.show.region.v1.RegionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lang', full_name='bilibili.app.show.region.v1.RegionReq.lang', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=98,
)


_REGIONREPLY = _descriptor.Descriptor(
  name='RegionReply',
  full_name='bilibili.app.show.region.v1.RegionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='regions', full_name='bilibili.app.show.region.v1.RegionReply.regions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=171,
)


_REGIONCONFIG = _descriptor.Descriptor(
  name='RegionConfig',
  full_name='bilibili.app.show.region.v1.RegionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='scenesName', full_name='bilibili.app.show.region.v1.RegionConfig.scenesName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scenesType', full_name='bilibili.app.show.region.v1.RegionConfig.scenesType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=227,
)


_REGIONINFO = _descriptor.Descriptor(
  name='RegionInfo',
  full_name='bilibili.app.show.region.v1.RegionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tid', full_name='bilibili.app.show.region.v1.RegionInfo.tid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reid', full_name='bilibili.app.show.region.v1.RegionInfo.reid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='bilibili.app.show.region.v1.RegionInfo.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logo', full_name='bilibili.app.show.region.v1.RegionInfo.logo', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goto', full_name='bilibili.app.show.region.v1.RegionInfo.goto', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param', full_name='bilibili.app.show.region.v1.RegionInfo.param', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='bilibili.app.show.region.v1.RegionInfo.uri', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='bilibili.app.show.region.v1.RegionInfo.type', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isBangumi', full_name='bilibili.app.show.region.v1.RegionInfo.isBangumi', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='children', full_name='bilibili.app.show.region.v1.RegionInfo.children', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config', full_name='bilibili.app.show.region.v1.RegionInfo.config', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=490,
)

_REGIONREPLY.fields_by_name['regions'].message_type = _REGIONINFO
_REGIONINFO.fields_by_name['children'].message_type = _REGIONINFO
_REGIONINFO.fields_by_name['config'].message_type = _REGIONCONFIG
DESCRIPTOR.message_types_by_name['RegionReq'] = _REGIONREQ
DESCRIPTOR.message_types_by_name['RegionReply'] = _REGIONREPLY
DESCRIPTOR.message_types_by_name['RegionConfig'] = _REGIONCONFIG
DESCRIPTOR.message_types_by_name['RegionInfo'] = _REGIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegionReq = _reflection.GeneratedProtocolMessageType('RegionReq', (_message.Message,), {
  'DESCRIPTOR' : _REGIONREQ,
  '__module__' : 'bilibili.app.show.region.v1.region_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.show.region.v1.RegionReq)
  })
_sym_db.RegisterMessage(RegionReq)

RegionReply = _reflection.GeneratedProtocolMessageType('RegionReply', (_message.Message,), {
  'DESCRIPTOR' : _REGIONREPLY,
  '__module__' : 'bilibili.app.show.region.v1.region_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.show.region.v1.RegionReply)
  })
_sym_db.RegisterMessage(RegionReply)

RegionConfig = _reflection.GeneratedProtocolMessageType('RegionConfig', (_message.Message,), {
  'DESCRIPTOR' : _REGIONCONFIG,
  '__module__' : 'bilibili.app.show.region.v1.region_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.show.region.v1.RegionConfig)
  })
_sym_db.RegisterMessage(RegionConfig)

RegionInfo = _reflection.GeneratedProtocolMessageType('RegionInfo', (_message.Message,), {
  'DESCRIPTOR' : _REGIONINFO,
  '__module__' : 'bilibili.app.show.region.v1.region_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.show.region.v1.RegionInfo)
  })
_sym_db.RegisterMessage(RegionInfo)



_REGION = _descriptor.ServiceDescriptor(
  name='Region',
  full_name='bilibili.app.show.region.v1.Region',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=492,
  serialized_end=592,
  methods=[
  _descriptor.MethodDescriptor(
    name='Region',
    full_name='bilibili.app.show.region.v1.Region.Region',
    index=0,
    containing_service=None,
    input_type=_REGIONREQ,
    output_type=_REGIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGION)

DESCRIPTOR.services_by_name['Region'] = _REGION

# @@protoc_insertion_point(module_scope)
