# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/api/probe/v1/probe.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/api/probe/v1/probe.proto',
  package='bilibili.api.probe.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!bilibili/api/probe/v1/probe.proto\x12\x15\x62ilibili.api.probe.v1\"\x17\n\x07\x43odeReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x03\"\x0b\n\tCodeReply\"&\n\x08ProbeReq\x12\x0b\n\x03mid\x18\x01 \x01(\x03\x12\r\n\x05\x62uvid\x18\x02 \x01(\t\"0\n\nProbeReply\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"/\n\x0eProbeStreamReq\x12\x0b\n\x03mid\x18\x01 \x01(\x03\x12\x10\n\x08sequence\x18\x02 \x01(\x03\"H\n\x10ProbeStreamReply\x12\x10\n\x08sequence\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x1c\n\x0bProbeSubReq\x12\r\n\x05\x62uvid\x18\x01 \x01(\x03\"\"\n\rProbeSubReply\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x32\xd7\x02\n\x05Probe\x12L\n\x08TestCode\x12\x1e.bilibili.api.probe.v1.CodeReq\x1a .bilibili.api.probe.v1.CodeReply\x12M\n\x07TestReq\x12\x1f.bilibili.api.probe.v1.ProbeReq\x1a!.bilibili.api.probe.v1.ProbeReply\x12\\\n\nTestStream\x12%.bilibili.api.probe.v1.ProbeStreamReq\x1a\'.bilibili.api.probe.v1.ProbeStreamReply\x12S\n\x07TestSub\x12\".bilibili.api.probe.v1.ProbeSubReq\x1a$.bilibili.api.probe.v1.ProbeSubReplyb\x06proto3'
)




_CODEREQ = _descriptor.Descriptor(
  name='CodeReq',
  full_name='bilibili.api.probe.v1.CodeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='bilibili.api.probe.v1.CodeReq.code', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=83,
)


_CODEREPLY = _descriptor.Descriptor(
  name='CodeReply',
  full_name='bilibili.api.probe.v1.CodeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=96,
)


_PROBEREQ = _descriptor.Descriptor(
  name='ProbeReq',
  full_name='bilibili.api.probe.v1.ProbeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mid', full_name='bilibili.api.probe.v1.ProbeReq.mid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buvid', full_name='bilibili.api.probe.v1.ProbeReq.buvid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=136,
)


_PROBEREPLY = _descriptor.Descriptor(
  name='ProbeReply',
  full_name='bilibili.api.probe.v1.ProbeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='bilibili.api.probe.v1.ProbeReply.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bilibili.api.probe.v1.ProbeReply.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=186,
)


_PROBESTREAMREQ = _descriptor.Descriptor(
  name='ProbeStreamReq',
  full_name='bilibili.api.probe.v1.ProbeStreamReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mid', full_name='bilibili.api.probe.v1.ProbeStreamReq.mid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='bilibili.api.probe.v1.ProbeStreamReq.sequence', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=235,
)


_PROBESTREAMREPLY = _descriptor.Descriptor(
  name='ProbeStreamReply',
  full_name='bilibili.api.probe.v1.ProbeStreamReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence', full_name='bilibili.api.probe.v1.ProbeStreamReply.sequence', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bilibili.api.probe.v1.ProbeStreamReply.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='bilibili.api.probe.v1.ProbeStreamReply.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=309,
)


_PROBESUBREQ = _descriptor.Descriptor(
  name='ProbeSubReq',
  full_name='bilibili.api.probe.v1.ProbeSubReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buvid', full_name='bilibili.api.probe.v1.ProbeSubReq.buvid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=339,
)


_PROBESUBREPLY = _descriptor.Descriptor(
  name='ProbeSubReply',
  full_name='bilibili.api.probe.v1.ProbeSubReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageId', full_name='bilibili.api.probe.v1.ProbeSubReply.messageId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=375,
)

DESCRIPTOR.message_types_by_name['CodeReq'] = _CODEREQ
DESCRIPTOR.message_types_by_name['CodeReply'] = _CODEREPLY
DESCRIPTOR.message_types_by_name['ProbeReq'] = _PROBEREQ
DESCRIPTOR.message_types_by_name['ProbeReply'] = _PROBEREPLY
DESCRIPTOR.message_types_by_name['ProbeStreamReq'] = _PROBESTREAMREQ
DESCRIPTOR.message_types_by_name['ProbeStreamReply'] = _PROBESTREAMREPLY
DESCRIPTOR.message_types_by_name['ProbeSubReq'] = _PROBESUBREQ
DESCRIPTOR.message_types_by_name['ProbeSubReply'] = _PROBESUBREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CodeReq = _reflection.GeneratedProtocolMessageType('CodeReq', (_message.Message,), {
  'DESCRIPTOR' : _CODEREQ,
  '__module__' : 'bilibili.api.probe.v1.probe_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.api.probe.v1.CodeReq)
  })
_sym_db.RegisterMessage(CodeReq)

CodeReply = _reflection.GeneratedProtocolMessageType('CodeReply', (_message.Message,), {
  'DESCRIPTOR' : _CODEREPLY,
  '__module__' : 'bilibili.api.probe.v1.probe_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.api.probe.v1.CodeReply)
  })
_sym_db.RegisterMessage(CodeReply)

ProbeReq = _reflection.GeneratedProtocolMessageType('ProbeReq', (_message.Message,), {
  'DESCRIPTOR' : _PROBEREQ,
  '__module__' : 'bilibili.api.probe.v1.probe_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.api.probe.v1.ProbeReq)
  })
_sym_db.RegisterMessage(ProbeReq)

ProbeReply = _reflection.GeneratedProtocolMessageType('ProbeReply', (_message.Message,), {
  'DESCRIPTOR' : _PROBEREPLY,
  '__module__' : 'bilibili.api.probe.v1.probe_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.api.probe.v1.ProbeReply)
  })
_sym_db.RegisterMessage(ProbeReply)

ProbeStreamReq = _reflection.GeneratedProtocolMessageType('ProbeStreamReq', (_message.Message,), {
  'DESCRIPTOR' : _PROBESTREAMREQ,
  '__module__' : 'bilibili.api.probe.v1.probe_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.api.probe.v1.ProbeStreamReq)
  })
_sym_db.RegisterMessage(ProbeStreamReq)

ProbeStreamReply = _reflection.GeneratedProtocolMessageType('ProbeStreamReply', (_message.Message,), {
  'DESCRIPTOR' : _PROBESTREAMREPLY,
  '__module__' : 'bilibili.api.probe.v1.probe_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.api.probe.v1.ProbeStreamReply)
  })
_sym_db.RegisterMessage(ProbeStreamReply)

ProbeSubReq = _reflection.GeneratedProtocolMessageType('ProbeSubReq', (_message.Message,), {
  'DESCRIPTOR' : _PROBESUBREQ,
  '__module__' : 'bilibili.api.probe.v1.probe_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.api.probe.v1.ProbeSubReq)
  })
_sym_db.RegisterMessage(ProbeSubReq)

ProbeSubReply = _reflection.GeneratedProtocolMessageType('ProbeSubReply', (_message.Message,), {
  'DESCRIPTOR' : _PROBESUBREPLY,
  '__module__' : 'bilibili.api.probe.v1.probe_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.api.probe.v1.ProbeSubReply)
  })
_sym_db.RegisterMessage(ProbeSubReply)



_PROBE = _descriptor.ServiceDescriptor(
  name='Probe',
  full_name='bilibili.api.probe.v1.Probe',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=378,
  serialized_end=721,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestCode',
    full_name='bilibili.api.probe.v1.Probe.TestCode',
    index=0,
    containing_service=None,
    input_type=_CODEREQ,
    output_type=_CODEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TestReq',
    full_name='bilibili.api.probe.v1.Probe.TestReq',
    index=1,
    containing_service=None,
    input_type=_PROBEREQ,
    output_type=_PROBEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TestStream',
    full_name='bilibili.api.probe.v1.Probe.TestStream',
    index=2,
    containing_service=None,
    input_type=_PROBESTREAMREQ,
    output_type=_PROBESTREAMREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TestSub',
    full_name='bilibili.api.probe.v1.Probe.TestSub',
    index=3,
    containing_service=None,
    input_type=_PROBESUBREQ,
    output_type=_PROBESUBREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROBE)

DESCRIPTOR.services_by_name['Probe'] = _PROBE

# @@protoc_insertion_point(module_scope)
