# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/app/wall/v1/wall.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/app/wall/v1/wall.proto',
  package='bilibili.app.wall.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x62ilibili/app/wall/v1/wall.proto\x12\x14\x62ilibili.app.wall.v1\"\r\n\x0bRuleRequest\"\xa3\x01\n\nRulesReply\x12\x42\n\trulesInfo\x18\x01 \x03(\x0b\x32/.bilibili.app.wall.v1.RulesReply.RulesInfoEntry\x1aQ\n\x0eRulesInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.bilibili.app.wall.v1.RulesInfo:\x02\x38\x01\"7\n\x08RuleInfo\x12\n\n\x02tf\x18\x01 \x01(\x08\x12\t\n\x01m\x18\x02 \x01(\t\x12\t\n\x01\x61\x18\x03 \x01(\t\x12\t\n\x01p\x18\x04 \x01(\t\">\n\tRulesInfo\x12\x31\n\trulesInfo\x18\x01 \x03(\x0b\x32\x1e.bilibili.app.wall.v1.RuleInfo2W\n\x04Wall\x12O\n\x08RuleInfo\x12!.bilibili.app.wall.v1.RuleRequest\x1a .bilibili.app.wall.v1.RulesReplyb\x06proto3'
)




_RULEREQUEST = _descriptor.Descriptor(
  name='RuleRequest',
  full_name='bilibili.app.wall.v1.RuleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=70,
)


_RULESREPLY_RULESINFOENTRY = _descriptor.Descriptor(
  name='RulesInfoEntry',
  full_name='bilibili.app.wall.v1.RulesReply.RulesInfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='bilibili.app.wall.v1.RulesReply.RulesInfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='bilibili.app.wall.v1.RulesReply.RulesInfoEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=236,
)

_RULESREPLY = _descriptor.Descriptor(
  name='RulesReply',
  full_name='bilibili.app.wall.v1.RulesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rulesInfo', full_name='bilibili.app.wall.v1.RulesReply.rulesInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RULESREPLY_RULESINFOENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=236,
)


_RULEINFO = _descriptor.Descriptor(
  name='RuleInfo',
  full_name='bilibili.app.wall.v1.RuleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tf', full_name='bilibili.app.wall.v1.RuleInfo.tf', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m', full_name='bilibili.app.wall.v1.RuleInfo.m', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='a', full_name='bilibili.app.wall.v1.RuleInfo.a', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='p', full_name='bilibili.app.wall.v1.RuleInfo.p', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=293,
)


_RULESINFO = _descriptor.Descriptor(
  name='RulesInfo',
  full_name='bilibili.app.wall.v1.RulesInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rulesInfo', full_name='bilibili.app.wall.v1.RulesInfo.rulesInfo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=357,
)

_RULESREPLY_RULESINFOENTRY.fields_by_name['value'].message_type = _RULESINFO
_RULESREPLY_RULESINFOENTRY.containing_type = _RULESREPLY
_RULESREPLY.fields_by_name['rulesInfo'].message_type = _RULESREPLY_RULESINFOENTRY
_RULESINFO.fields_by_name['rulesInfo'].message_type = _RULEINFO
DESCRIPTOR.message_types_by_name['RuleRequest'] = _RULEREQUEST
DESCRIPTOR.message_types_by_name['RulesReply'] = _RULESREPLY
DESCRIPTOR.message_types_by_name['RuleInfo'] = _RULEINFO
DESCRIPTOR.message_types_by_name['RulesInfo'] = _RULESINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RuleRequest = _reflection.GeneratedProtocolMessageType('RuleRequest', (_message.Message,), {
  'DESCRIPTOR' : _RULEREQUEST,
  '__module__' : 'bilibili.app.wall.v1.wall_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.wall.v1.RuleRequest)
  })
_sym_db.RegisterMessage(RuleRequest)

RulesReply = _reflection.GeneratedProtocolMessageType('RulesReply', (_message.Message,), {

  'RulesInfoEntry' : _reflection.GeneratedProtocolMessageType('RulesInfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _RULESREPLY_RULESINFOENTRY,
    '__module__' : 'bilibili.app.wall.v1.wall_pb2'
    # @@protoc_insertion_point(class_scope:bilibili.app.wall.v1.RulesReply.RulesInfoEntry)
    })
  ,
  'DESCRIPTOR' : _RULESREPLY,
  '__module__' : 'bilibili.app.wall.v1.wall_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.wall.v1.RulesReply)
  })
_sym_db.RegisterMessage(RulesReply)
_sym_db.RegisterMessage(RulesReply.RulesInfoEntry)

RuleInfo = _reflection.GeneratedProtocolMessageType('RuleInfo', (_message.Message,), {
  'DESCRIPTOR' : _RULEINFO,
  '__module__' : 'bilibili.app.wall.v1.wall_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.wall.v1.RuleInfo)
  })
_sym_db.RegisterMessage(RuleInfo)

RulesInfo = _reflection.GeneratedProtocolMessageType('RulesInfo', (_message.Message,), {
  'DESCRIPTOR' : _RULESINFO,
  '__module__' : 'bilibili.app.wall.v1.wall_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.wall.v1.RulesInfo)
  })
_sym_db.RegisterMessage(RulesInfo)


_RULESREPLY_RULESINFOENTRY._options = None

_WALL = _descriptor.ServiceDescriptor(
  name='Wall',
  full_name='bilibili.app.wall.v1.Wall',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=359,
  serialized_end=446,
  methods=[
  _descriptor.MethodDescriptor(
    name='RuleInfo',
    full_name='bilibili.app.wall.v1.Wall.RuleInfo',
    index=0,
    containing_service=None,
    input_type=_RULEREQUEST,
    output_type=_RULESREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WALL)

DESCRIPTOR.services_by_name['Wall'] = _WALL

# @@protoc_insertion_point(module_scope)
