# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/account/fission/v1/fission.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/account/fission/v1/fission.proto',
  package='bilibili.account.fission.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)bilibili/account/fission/v1/fission.proto\x12\x1b\x62ilibili.account.fission.v1\"\r\n\x0b\x45ntranceReq\"w\n\rEntranceReply\x12\x0c\n\x04icon\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12=\n\x0b\x61nimateIcon\x18\x04 \x01(\x0b\x32(.bilibili.account.fission.v1.AnimateIcon\"\x0b\n\tWindowReq\"<\n\x0bWindowReply\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x12\n\nreportData\x18\x03 \x01(\t\")\n\x0b\x41nimateIcon\x12\x0c\n\x04icon\x18\x01 \x01(\t\x12\x0c\n\x04json\x18\x02 \x01(\t2\xc7\x01\n\x07\x46ission\x12`\n\x08\x45ntrance\x12(.bilibili.account.fission.v1.EntranceReq\x1a*.bilibili.account.fission.v1.EntranceReply\x12Z\n\x06Window\x12&.bilibili.account.fission.v1.WindowReq\x1a(.bilibili.account.fission.v1.WindowReplyb\x06proto3'
)




_ENTRANCEREQ = _descriptor.Descriptor(
  name='EntranceReq',
  full_name='bilibili.account.fission.v1.EntranceReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=87,
)


_ENTRANCEREPLY = _descriptor.Descriptor(
  name='EntranceReply',
  full_name='bilibili.account.fission.v1.EntranceReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='icon', full_name='bilibili.account.fission.v1.EntranceReply.icon', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='bilibili.account.fission.v1.EntranceReply.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='bilibili.account.fission.v1.EntranceReply.url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='animateIcon', full_name='bilibili.account.fission.v1.EntranceReply.animateIcon', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=208,
)


_WINDOWREQ = _descriptor.Descriptor(
  name='WindowReq',
  full_name='bilibili.account.fission.v1.WindowReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=221,
)


_WINDOWREPLY = _descriptor.Descriptor(
  name='WindowReply',
  full_name='bilibili.account.fission.v1.WindowReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='bilibili.account.fission.v1.WindowReply.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='bilibili.account.fission.v1.WindowReply.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reportData', full_name='bilibili.account.fission.v1.WindowReply.reportData', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=283,
)


_ANIMATEICON = _descriptor.Descriptor(
  name='AnimateIcon',
  full_name='bilibili.account.fission.v1.AnimateIcon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='icon', full_name='bilibili.account.fission.v1.AnimateIcon.icon', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='json', full_name='bilibili.account.fission.v1.AnimateIcon.json', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=326,
)

_ENTRANCEREPLY.fields_by_name['animateIcon'].message_type = _ANIMATEICON
DESCRIPTOR.message_types_by_name['EntranceReq'] = _ENTRANCEREQ
DESCRIPTOR.message_types_by_name['EntranceReply'] = _ENTRANCEREPLY
DESCRIPTOR.message_types_by_name['WindowReq'] = _WINDOWREQ
DESCRIPTOR.message_types_by_name['WindowReply'] = _WINDOWREPLY
DESCRIPTOR.message_types_by_name['AnimateIcon'] = _ANIMATEICON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EntranceReq = _reflection.GeneratedProtocolMessageType('EntranceReq', (_message.Message,), {
  'DESCRIPTOR' : _ENTRANCEREQ,
  '__module__' : 'bilibili.account.fission.v1.fission_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.account.fission.v1.EntranceReq)
  })
_sym_db.RegisterMessage(EntranceReq)

EntranceReply = _reflection.GeneratedProtocolMessageType('EntranceReply', (_message.Message,), {
  'DESCRIPTOR' : _ENTRANCEREPLY,
  '__module__' : 'bilibili.account.fission.v1.fission_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.account.fission.v1.EntranceReply)
  })
_sym_db.RegisterMessage(EntranceReply)

WindowReq = _reflection.GeneratedProtocolMessageType('WindowReq', (_message.Message,), {
  'DESCRIPTOR' : _WINDOWREQ,
  '__module__' : 'bilibili.account.fission.v1.fission_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.account.fission.v1.WindowReq)
  })
_sym_db.RegisterMessage(WindowReq)

WindowReply = _reflection.GeneratedProtocolMessageType('WindowReply', (_message.Message,), {
  'DESCRIPTOR' : _WINDOWREPLY,
  '__module__' : 'bilibili.account.fission.v1.fission_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.account.fission.v1.WindowReply)
  })
_sym_db.RegisterMessage(WindowReply)

AnimateIcon = _reflection.GeneratedProtocolMessageType('AnimateIcon', (_message.Message,), {
  'DESCRIPTOR' : _ANIMATEICON,
  '__module__' : 'bilibili.account.fission.v1.fission_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.account.fission.v1.AnimateIcon)
  })
_sym_db.RegisterMessage(AnimateIcon)



_FISSION = _descriptor.ServiceDescriptor(
  name='Fission',
  full_name='bilibili.account.fission.v1.Fission',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=329,
  serialized_end=528,
  methods=[
  _descriptor.MethodDescriptor(
    name='Entrance',
    full_name='bilibili.account.fission.v1.Fission.Entrance',
    index=0,
    containing_service=None,
    input_type=_ENTRANCEREQ,
    output_type=_ENTRANCEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Window',
    full_name='bilibili.account.fission.v1.Fission.Window',
    index=1,
    containing_service=None,
    input_type=_WINDOWREQ,
    output_type=_WINDOWREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FISSION)

DESCRIPTOR.services_by_name['Fission'] = _FISSION

# @@protoc_insertion_point(module_scope)
