# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/app/space/v1/space.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/app/space/v1/space.proto',
  package='bilibili.app.space.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!bilibili/app/space/v1/space.proto\x12\x15\x62ilibili.app.space.v1\"A\n\nArchiveReq\x12\x0c\n\x04vmid\x18\x01 \x01(\x03\x12\n\n\x02pn\x18\x02 \x01(\x05\x12\n\n\x02ps\x18\x03 \x01(\x05\x12\r\n\x05order\x18\x04 \x01(\t\"\xc4\x01\n\x0c\x41rchiveReply\x12\x33\n\x04item\x18\x01 \x03(\x0b\x32%.bilibili.app.space.v1.BiliSpaceVideo\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12=\n\x0e\x65pisodicButton\x18\x03 \x01(\x0b\x32%.bilibili.app.space.v1.EpisodicButton\x12\x31\n\x05order\x18\x04 \x03(\x0b\x32\".bilibili.app.space.v1.OrderConfig\"\xa7\x01\n\x05\x42\x61\x64ge\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\ttextColor\x18\x02 \x01(\t\x12\x16\n\x0etextColorNight\x18\x03 \x01(\t\x12\x0f\n\x07\x62gColor\x18\x04 \x01(\t\x12\x14\n\x0c\x62gColorNight\x18\x05 \x01(\t\x12\x13\n\x0b\x62orderColor\x18\x06 \x01(\t\x12\x18\n\x10\x62orderColorNight\x18\x07 \x01(\t\x12\x0f\n\x07\x62gStyle\x18\x08 \x01(\x05\"\xc6\x02\n\x0e\x42iliSpaceVideo\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05tname\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\x03\x12\r\n\x05\x63over\x18\x04 \x01(\t\x12\x0b\n\x03uri\x18\x05 \x01(\t\x12\r\n\x05param\x18\x06 \x01(\t\x12\x0f\n\x07\x64\x61nmaku\x18\x07 \x01(\t\x12\x0c\n\x04play\x18\x08 \x01(\x05\x12\r\n\x05\x63time\x18\t \x01(\x03\x12\r\n\x05state\x18\n \x01(\x08\x12\x11\n\tisPopular\x18\x0b \x01(\x08\x12,\n\x06\x62\x61\x64ges\x18\x0c \x03(\x0b\x32\x1c.bilibili.app.space.v1.Badge\x12\x12\n\ncoverRight\x18\r \x01(\t\x12\x0c\n\x04\x62vid\x18\x0e \x01(\t\x12\x10\n\x08isSteins\x18\x0f \x01(\x08\x12\x10\n\x08isUgcpay\x18\x10 \x01(\x08\x12\x15\n\risCooperation\x18\x11 \x01(\x08\"+\n\x0e\x45pisodicButton\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\"+\n\x0bOrderConfig\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2Z\n\x05Space\x12Q\n\x07\x41rchive\x12!.bilibili.app.space.v1.ArchiveReq\x1a#.bilibili.app.space.v1.ArchiveReplyb\x06proto3'
)




_ARCHIVEREQ = _descriptor.Descriptor(
  name='ArchiveReq',
  full_name='bilibili.app.space.v1.ArchiveReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vmid', full_name='bilibili.app.space.v1.ArchiveReq.vmid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pn', full_name='bilibili.app.space.v1.ArchiveReq.pn', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ps', full_name='bilibili.app.space.v1.ArchiveReq.ps', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order', full_name='bilibili.app.space.v1.ArchiveReq.order', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=125,
)


_ARCHIVEREPLY = _descriptor.Descriptor(
  name='ArchiveReply',
  full_name='bilibili.app.space.v1.ArchiveReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='bilibili.app.space.v1.ArchiveReply.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='bilibili.app.space.v1.ArchiveReply.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='episodicButton', full_name='bilibili.app.space.v1.ArchiveReply.episodicButton', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order', full_name='bilibili.app.space.v1.ArchiveReply.order', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=324,
)


_BADGE = _descriptor.Descriptor(
  name='Badge',
  full_name='bilibili.app.space.v1.Badge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='bilibili.app.space.v1.Badge.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='textColor', full_name='bilibili.app.space.v1.Badge.textColor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='textColorNight', full_name='bilibili.app.space.v1.Badge.textColorNight', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bgColor', full_name='bilibili.app.space.v1.Badge.bgColor', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bgColorNight', full_name='bilibili.app.space.v1.Badge.bgColorNight', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='borderColor', full_name='bilibili.app.space.v1.Badge.borderColor', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='borderColorNight', full_name='bilibili.app.space.v1.Badge.borderColorNight', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bgStyle', full_name='bilibili.app.space.v1.Badge.bgStyle', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=494,
)


_BILISPACEVIDEO = _descriptor.Descriptor(
  name='BiliSpaceVideo',
  full_name='bilibili.app.space.v1.BiliSpaceVideo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='bilibili.app.space.v1.BiliSpaceVideo.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tname', full_name='bilibili.app.space.v1.BiliSpaceVideo.tname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='bilibili.app.space.v1.BiliSpaceVideo.duration', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cover', full_name='bilibili.app.space.v1.BiliSpaceVideo.cover', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='bilibili.app.space.v1.BiliSpaceVideo.uri', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='param', full_name='bilibili.app.space.v1.BiliSpaceVideo.param', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='danmaku', full_name='bilibili.app.space.v1.BiliSpaceVideo.danmaku', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='play', full_name='bilibili.app.space.v1.BiliSpaceVideo.play', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ctime', full_name='bilibili.app.space.v1.BiliSpaceVideo.ctime', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='bilibili.app.space.v1.BiliSpaceVideo.state', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isPopular', full_name='bilibili.app.space.v1.BiliSpaceVideo.isPopular', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='badges', full_name='bilibili.app.space.v1.BiliSpaceVideo.badges', index=11,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='coverRight', full_name='bilibili.app.space.v1.BiliSpaceVideo.coverRight', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bvid', full_name='bilibili.app.space.v1.BiliSpaceVideo.bvid', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isSteins', full_name='bilibili.app.space.v1.BiliSpaceVideo.isSteins', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isUgcpay', full_name='bilibili.app.space.v1.BiliSpaceVideo.isUgcpay', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isCooperation', full_name='bilibili.app.space.v1.BiliSpaceVideo.isCooperation', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=823,
)


_EPISODICBUTTON = _descriptor.Descriptor(
  name='EpisodicButton',
  full_name='bilibili.app.space.v1.EpisodicButton',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='bilibili.app.space.v1.EpisodicButton.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uri', full_name='bilibili.app.space.v1.EpisodicButton.uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=825,
  serialized_end=868,
)


_ORDERCONFIG = _descriptor.Descriptor(
  name='OrderConfig',
  full_name='bilibili.app.space.v1.OrderConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='bilibili.app.space.v1.OrderConfig.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='bilibili.app.space.v1.OrderConfig.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=870,
  serialized_end=913,
)

_ARCHIVEREPLY.fields_by_name['item'].message_type = _BILISPACEVIDEO
_ARCHIVEREPLY.fields_by_name['episodicButton'].message_type = _EPISODICBUTTON
_ARCHIVEREPLY.fields_by_name['order'].message_type = _ORDERCONFIG
_BILISPACEVIDEO.fields_by_name['badges'].message_type = _BADGE
DESCRIPTOR.message_types_by_name['ArchiveReq'] = _ARCHIVEREQ
DESCRIPTOR.message_types_by_name['ArchiveReply'] = _ARCHIVEREPLY
DESCRIPTOR.message_types_by_name['Badge'] = _BADGE
DESCRIPTOR.message_types_by_name['BiliSpaceVideo'] = _BILISPACEVIDEO
DESCRIPTOR.message_types_by_name['EpisodicButton'] = _EPISODICBUTTON
DESCRIPTOR.message_types_by_name['OrderConfig'] = _ORDERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArchiveReq = _reflection.GeneratedProtocolMessageType('ArchiveReq', (_message.Message,), {
  'DESCRIPTOR' : _ARCHIVEREQ,
  '__module__' : 'bilibili.app.space.v1.space_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.space.v1.ArchiveReq)
  })
_sym_db.RegisterMessage(ArchiveReq)

ArchiveReply = _reflection.GeneratedProtocolMessageType('ArchiveReply', (_message.Message,), {
  'DESCRIPTOR' : _ARCHIVEREPLY,
  '__module__' : 'bilibili.app.space.v1.space_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.space.v1.ArchiveReply)
  })
_sym_db.RegisterMessage(ArchiveReply)

Badge = _reflection.GeneratedProtocolMessageType('Badge', (_message.Message,), {
  'DESCRIPTOR' : _BADGE,
  '__module__' : 'bilibili.app.space.v1.space_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.space.v1.Badge)
  })
_sym_db.RegisterMessage(Badge)

BiliSpaceVideo = _reflection.GeneratedProtocolMessageType('BiliSpaceVideo', (_message.Message,), {
  'DESCRIPTOR' : _BILISPACEVIDEO,
  '__module__' : 'bilibili.app.space.v1.space_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.space.v1.BiliSpaceVideo)
  })
_sym_db.RegisterMessage(BiliSpaceVideo)

EpisodicButton = _reflection.GeneratedProtocolMessageType('EpisodicButton', (_message.Message,), {
  'DESCRIPTOR' : _EPISODICBUTTON,
  '__module__' : 'bilibili.app.space.v1.space_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.space.v1.EpisodicButton)
  })
_sym_db.RegisterMessage(EpisodicButton)

OrderConfig = _reflection.GeneratedProtocolMessageType('OrderConfig', (_message.Message,), {
  'DESCRIPTOR' : _ORDERCONFIG,
  '__module__' : 'bilibili.app.space.v1.space_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.app.space.v1.OrderConfig)
  })
_sym_db.RegisterMessage(OrderConfig)



_SPACE = _descriptor.ServiceDescriptor(
  name='Space',
  full_name='bilibili.app.space.v1.Space',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=915,
  serialized_end=1005,
  methods=[
  _descriptor.MethodDescriptor(
    name='Archive',
    full_name='bilibili.app.space.v1.Space.Archive',
    index=0,
    containing_service=None,
    input_type=_ARCHIVEREQ,
    output_type=_ARCHIVEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPACE)

DESCRIPTOR.services_by_name['Space'] = _SPACE

# @@protoc_insertion_point(module_scope)
