# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilibili/metadata/fawkes/fawkes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bilibili/metadata/fawkes/fawkes.proto',
  package='bilibili.metadata.fawkes',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%bilibili/metadata/fawkes/fawkes.proto\x12\x18\x62ilibili.metadata.fawkes\"<\n\tFawkesReq\x12\x0e\n\x06\x61ppkey\x18\x01 \x01(\t\x12\x0b\n\x03\x65nv\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\")\n\x0b\x46\x61wkesReply\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\x12\n\n\x02\x66\x66\x18\x02 \x01(\tb\x06proto3'
)




_FAWKESREQ = _descriptor.Descriptor(
  name='FawkesReq',
  full_name='bilibili.metadata.fawkes.FawkesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appkey', full_name='bilibili.metadata.fawkes.FawkesReq.appkey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='env', full_name='bilibili.metadata.fawkes.FawkesReq.env', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='bilibili.metadata.fawkes.FawkesReq.session_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=127,
)


_FAWKESREPLY = _descriptor.Descriptor(
  name='FawkesReply',
  full_name='bilibili.metadata.fawkes.FawkesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='bilibili.metadata.fawkes.FawkesReply.config', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ff', full_name='bilibili.metadata.fawkes.FawkesReply.ff', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['FawkesReq'] = _FAWKESREQ
DESCRIPTOR.message_types_by_name['FawkesReply'] = _FAWKESREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FawkesReq = _reflection.GeneratedProtocolMessageType('FawkesReq', (_message.Message,), {
  'DESCRIPTOR' : _FAWKESREQ,
  '__module__' : 'bilibili.metadata.fawkes.fawkes_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.metadata.fawkes.FawkesReq)
  })
_sym_db.RegisterMessage(FawkesReq)

FawkesReply = _reflection.GeneratedProtocolMessageType('FawkesReply', (_message.Message,), {
  'DESCRIPTOR' : _FAWKESREPLY,
  '__module__' : 'bilibili.metadata.fawkes.fawkes_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.metadata.fawkes.FawkesReply)
  })
_sym_db.RegisterMessage(FawkesReply)


# @@protoc_insertion_point(module_scope)
